//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtEntities : DbContext
    {
        public ArtEntities()
            : base("name=ArtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatternMaster> PatternMasters { get; set; }
        public virtual DbSet<PatterRefMaster> PatterRefMasters { get; set; }
        public virtual DbSet<PatternStyle> PatternStyles { get; set; }
        public virtual DbSet<BuyerMaster> BuyerMasters { get; set; }
        public virtual DbSet<SampleType> SampleTypes { get; set; }
        public virtual DbSet<SamCutAssignmentMaster> SamCutAssignmentMasters { get; set; }
        public virtual DbSet<SamplingFabricMaster> SamplingFabricMasters { get; set; }
        public virtual DbSet<SamplingView> SamplingViews { get; set; }
        public virtual DbSet<SamCutPlanPriority> SamCutPlanPriorities { get; set; }
        public virtual DbSet<SamSewingPriority> SamSewingPriorities { get; set; }
        public virtual DbSet<SampCutReqMaster> SampCutReqMasters { get; set; }
        public virtual DbSet<SamDailySewStatu> SamDailySewStatus { get; set; }
        public virtual DbSet<SamDailyDeliveryStatu> SamDailyDeliveryStatus { get; set; }
        public virtual DbSet<SamDailyCutStatu> SamDailyCutStatus { get; set; }
    }
}
