//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyerMaster()
        {
            this.SampCutReqMasters = new HashSet<SampCutReqMaster>();
        }
    
        public decimal BuyerID { get; set; }
        public string BuyerName { get; set; }
        public string Prefix { get; set; }
        public string Adress { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<decimal> CountryCode { get; set; }
        public Nullable<decimal> CurrencyCode { get; set; }
        public Nullable<decimal> PaymentModeCode { get; set; }
        public string Department { get; set; }
        public string Agent { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> AccountCode { get; set; }
        public Nullable<decimal> Debitaccid { get; set; }
        public string Br { get; set; }
        public Nullable<decimal> partner_id { get; set; }
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampCutReqMaster> SampCutReqMasters { get; set; }
    }
}
