//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatternMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatternMaster()
        {
            this.SamCutAssignmentMasters = new HashSet<SamCutAssignmentMaster>();
        }
    
        public decimal PatternMasterID { get; set; }
        public string PaternMasterName { get; set; }
        public bool IsActive { get; set; }
        public string Username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamCutAssignmentMaster> SamCutAssignmentMasters { get; set; }
    }
}
