//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamCutAssignmentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SamCutAssignmentMaster()
        {
            this.SamCutPlanPriorities = new HashSet<SamCutPlanPriority>();
            this.SamSewingPriorities = new HashSet<SamSewingPriority>();
        }
    
        public decimal CutAssignID { get; set; }
        public decimal SampCutreqID { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<decimal> PatternMasterID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public bool SignedBYMaster { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Remark { get; set; }
        public string MarkedCompletedBY { get; set; }
        public Nullable<System.DateTime> PatternReqDate { get; set; }
        public Nullable<System.DateTime> PatternCompletedDate { get; set; }
        public Nullable<decimal> SamplingStatus_PK { get; set; }
        public Nullable<decimal> CompletedQty { get; set; }
        public string PendingReason { get; set; }
    
        public virtual PatternMaster PatternMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamCutPlanPriority> SamCutPlanPriorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SamSewingPriority> SamSewingPriorities { get; set; }
        public virtual SampCutReqMaster SampCutReqMaster { get; set; }
    }
}
