//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamDailySewStatu
    {
        public decimal SamSewingDailyId { get; set; }
        public Nullable<decimal> SampCutreqID { get; set; }
        public Nullable<decimal> Size1SewtQty { get; set; }
        public Nullable<decimal> Size2SewQty { get; set; }
        public Nullable<decimal> Size3SewQty { get; set; }
        public Nullable<decimal> Size4SewQty { get; set; }
        public Nullable<decimal> Size5SewQty { get; set; }
        public Nullable<decimal> Size6SewQty { get; set; }
        public Nullable<System.DateTime> DateofAction { get; set; }
    
        public virtual SampCutReqMaster SampCutReqMaster { get; set; }
    }
}
