//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamDailyDeliveryStatu
    {
        public decimal SamDeliveryDailyId { get; set; }
        public Nullable<decimal> SampCutreqID { get; set; }
        public Nullable<decimal> Size1DeliveryQty { get; set; }
        public Nullable<decimal> Size2DeliveryQty { get; set; }
        public Nullable<decimal> Size3DeliveryQty { get; set; }
        public Nullable<decimal> Size4DeliveryQty { get; set; }
        public Nullable<decimal> Size5DeliveryQty { get; set; }
        public Nullable<decimal> Size6DeliveryQty { get; set; }
        public Nullable<System.DateTime> DateofAction { get; set; }
    
        public virtual SampCutReqMaster SampCutReqMaster { get; set; }
    }
}
