//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArtSampler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplingView
    {
        public string ReqNum { get; set; }
        public string Fabric { get; set; }
        public string StyleDescription { get; set; }
        public string BuyerName { get; set; }
        public string PatterRefNum { get; set; }
        public string StyleName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string ReceivedBy { get; set; }
        public bool SignedBYMaster { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Remark { get; set; }
        public string MarkedCompletedBY { get; set; }
        public string PaternMasterName { get; set; }
        public decimal PatternMasterID { get; set; }
        public string SampleType { get; set; }
        public Nullable<System.DateTime> SampleRequiredDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> PatternReqDate { get; set; }
        public decimal BuyerID { get; set; }
        public decimal SampleTypeID { get; set; }
        public Nullable<decimal> CompletedQty { get; set; }
        public string PendingReason { get; set; }
        public Nullable<System.DateTime> PatternCompletedDate { get; set; }
        public string SizeDetail { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Expr1 { get; set; }
        public bool IsTeckPack { get; set; }
        public string IsReceived { get; set; }
        public string IsPatternCompleted { get; set; }
    }
}
